/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcessoAdminRouteImport } from './routes/acesso-admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedSalaRouteImport } from './routes/_authenticated/sala'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoAdminRoute = AcessoAdminRouteImport.update({
  id: '/acesso-admin',
  path: '/acesso-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalaRoute = AuthenticatedSalaRouteImport.update({
  id: '/sala',
  path: '/sala',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-admin': typeof AcessoAdminRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/sala': typeof AuthenticatedSalaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-admin': typeof AcessoAdminRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/sala': typeof AuthenticatedSalaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acesso-admin': typeof AcessoAdminRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/sala': typeof AuthenticatedSalaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/acesso-admin' | '/auth' | '/admin' | '/painel' | '/perfil' | '/sala'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/acesso-admin' | '/auth' | '/admin' | '/painel' | '/perfil' | '/sala'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acesso-admin'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/sala'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessoAdminRoute: typeof AcessoAdminRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-admin': {
      id: '/acesso-admin'
      path: '/acesso-admin'
      fullPath: '/acesso-admin'
      preLoaderRoute: typeof AcessoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sala': {
      id: '/_authenticated/sala'
      path: '/sala'
      fullPath: '/sala'
      preLoaderRoute: typeof AuthenticatedSalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSalaRoute: typeof AuthenticatedSalaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSalaRoute: AuthenticatedSalaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessoAdminRoute: AcessoAdminRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
